--- #YAML:1.0
name: Acme-Innuendo
version: 0.02
author: Robert Rothenberg <rrwo at cpan.org>
abstract: polite access to Perl's private parts
license: perl
requires:
  Exporter::Lite: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.25
